class ResponseError(Exception): ...

class UnnecessaryResponseError(ResponseError): ...
class HeaderAlreadySentError(UnnecessaryResponseError): ...
class ResponsingError(UnnecessaryResponseError): ...
class StreamAlreadyClosedError(UnnecessaryResponseError): ...

class NecessaryResponseError(ResponseError): ...
class NoMoreStreamDataError(NecessaryResponseError): ...
class NoResponseError(NecessaryResponseError): ...


# EOF